openapi: 3.0.3
info:
  version: "1.0.0"
  title: Astro Search API
  description: 「Astro Search」用のAPI

paths:
  /admin/initialize:
    post:
      summary: Cosmos DB の初期化
      description: Cosmos DB のデータベースとコンテナ（access, actions, search_result）を作成します（存在しない場合のみ）。主にローカル・開発環境向け。
      responses:
        "200":
          description: 初期化成功
        "500":
          description: 初期化処理でエラーが発生

  /admin/seed:
    post:
      summary: 旧テストデータの削除と、seedのテストデータの投入。ローカルと開発環境だけで動作し、本番環境では実行されない
      description: Cosmos DB の旧データを削除し、テストデータ（access, actions, search_result 各コンテナ）を投入します。
      responses:
        "200":
          description: データ投入成功
        "500":
          description: テストデータ投入に失敗

components:
  schemas:
    SearchResults:
      type: object
      properties:
        results:
          type: array
          items:
            type: object
            properties:
              place_id:
                type: string
              name:
                type: string
              description:
                type: string

    PlaceDetails:
      type: object
      properties:
        place_id:
          type: string
        name:
          type: string
        address:
          type: string
        lat:
          type: number
          format: float
        lng:
          type: number
          format: float
        map_url:
          type: string

