authorization: none  
encryption: none    
transport_security:
  protocol: HTTPS
  tls_version: TLS 1.2

session_control: none  # セッション単位の識別はしているが、制御なし

vulnerabilities:
  html_injection: not applicable
  js_injection: not applicable
  csrf: not applicable  # フォーム投稿やセッションがないので脅威なし

audit:
  exception_logging: enabled
  destination: Azure Application Insights
  alerting: none

privacy_policy: not required  # 個人情報を保持しないため
personal_data_deletion: not required  # 個人情報を保持しないため
secret_key: 
  google_places_api:
    variable: GooglePlacesApiKey
    usage: 外部地名検索用のAPI(textsearch, details)
    storage:
      local: local.setting.json に保存（ローカル限定）
      development: Azure Key Vault で保護
      production: Azure Key Vault で保護
    scope: Infrastructure層(PlacesClient)でのみ使用
  cosmos_db_connection_string:
    variable: CosmosDbConnection
    usage: Cosmos DBへの接続文字列
    storage:
      local: local.setting.json に保存（ローカル限定）
      development: Azure Key Vault で保護
      production: Azure Key Vault で保護      
    scope: Infrastructure層(PlacesClient)でのみ使用
